#!/bin/bash
echo "========================================="
echo "Git Push Helper"
echo "========================================="
echo ""
echo "Please run the following command:"
echo ""
echo "git push"
echo ""
echo "If asked for credentials, enter your GitHub Personal Access Token as password"
echo ""
echo "Or use:"
echo "git push https://YOUR_TOKEN@github.com/IKEMENLTD/gasgenerator.git main"
echo ""
