#!/bin/bash
echo "====================================="
echo "  Render CLI Deployment"
echo "====================================="
echo ""
echo "First, you need to login to Render:"
echo ""
echo "1. Go to: https://dashboard.render.com/u/settings"
echo "2. Click on 'API Keys'"
echo "3. Create a new API key"
echo "4. Copy the API key"
echo ""
echo "Then run:"
echo "render login --api-key YOUR_API_KEY"
echo ""
echo "After login, run:"
echo "render deploy --service-id YOUR_SERVICE_ID"
echo ""
echo "To find your service ID:"
echo "Go to your Render service dashboard"
echo "The URL will be: https://dashboard.render.com/web/srv-XXXXX"
echo "srv-XXXXX is your service ID"
echo ""